---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: prod
spec:
  encryptedData:
    password: AgC3BUP+YHDfJ+ijveM9sobxBo6a12Qq1urj8LrQeWTrzlZtpiW+YV6N+udZPVmDztlxNvP6MaAsPo9Cgpi6TDXkM+QIp3X5zftxblQg9n2T/kYLc1Eej5M4R0YTsaD/uqHRDukjBkY3kWA4n//8a9vsp2h1NtgFP7tECp0y1IMssK8b1WJatyvJJiGN0AKVU+0oxhRffFXKlvdzN+NJFnGRnRhwL7XEsv2vDEV2BFe7RJmPtNfwUyYlmwocqYX5iGH7o4Q8IdTqLwRvu5mjhLfhslKXg1cVupK157cfc6chniDPuptF2r0fHLyGboHaYcVcONnkTODp5wZUWcVchvdBSICy5eUumgOTFoGBZ3/qQ2KY/7zgw1n9P7amP5ImQuNFd6Qty4Lws+AYFAhX2vfUblxhH/u/65VRtlVaIR6EcWTJh/fUM4oDnk/RVYQQuycuSnhwN0mGOAbvMftxqwF37ke48Et/3mRZ9AjyQv3vE8XtF7n5T/xRxhsL1kqRyLBb5JJUXEz4DpaYwzuvg8DykeJ7EDtolP+dIkCWGYo22m/9ptPhwdfPJ07BsHF1ZmwlK8grRcR9NHJt629qutMHM4ePFRGkIJ8k2C8WJTOKq5ZAPhYLl5WM9SoMcLNxx6fd8VlbPoaAyPVE2tph9Bjv4BfoMdI73mUzCqrYCSF63K9iODKfzmJs8SsySFm0pKgUdQ8e2ejVnWF8/8JKfd7lbeycC/5T1c435Y0E5WTGN3E9gp3J7R+PzPqtqh28IIU=
    user: AgAka68oOetIhcYND6H7qLt0h8kL7/EC7NytUp7LqZsT6I5jcv7qIeXlVYdQXMCk0x99wD3mpkfsCIyS86z7vj3Wz+MNWijKqk6x4X5rKJFfiXOxKik4WzIzqv6Vatlrk7pJ2gSwPzBO8VDmnq5kLHV4vgizA/nRbFYFc/o+fnehxAG2TDk7IrklQACdWAC5ZFyTlj1wr9xvVxhubWAC65N5D7hzEtRbJFybUXz9pjG1PusXlZBdUaHwcixJc1JyH3EFbpeEPDpHV5xZbU+h6HhYFmGtftoCRVvNBYsTMYVjnR6T8qKSIJQ3Amin6r68SVIEDYVf7St4JAIUoMBcNf15sI6ojwkIarUo9/+qLTNi07lXaQBuQKW1g5dzuqJYCtorIXv2HA0zVm4QiAs/bvAlJm7maeewl9DWZ38bXTyiCsDllnNhOMkROgj6LuhqnJl/oJ4pD4TZFP+0d4nA3rNfQAIQ3N/vNgLTDgcv5fVPgRm8HLDMgCMpweUdEHfacl/IQnQM0oeJ8xgLAR0wgqi1h/xv2v0T83RPqg7fSjNJCmxzQqvZjYL+olYFlm6mLLAFxadSXCaBAHqQOT8U3WOgvDHOkiNaGIpeF+RhdYVEBNC6Yqk9fOhlBIDL80zV/AroLhqIG9XnJc4vTPDaGCOYxfSYyBjWHtPRKTUSk8ZRg1MZj5MXUzkDBx9J5gYwovAx08g=
  template:
    metadata:
      name: postgres-credentials
      namespace: prod
