---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAFtqkagTLvpVJZgJr5tU7KVP7/i+nUdIP38Z7QSsWlHjbMqH+lcIe7/+9PNLEzO5avK5VLkBZpMTst9iYOa/qIa0D/WVmIblwWCw2V1SdmrmFKM8wN4YPOBYpVf5RAKpl3+PeViEqqwh2xcrFNwBy+a8RftIzMsX4G0Tgc+iaVayyL0rWNgPMjKS+wz52k01CNKExIv8nKQyBf675SvpSe3LKggMHE/ird9lrsUL6Z+7hwkRgE0cWLsvenZ2WNyoB4Rfdf8g/fwReIdIzN1MvpLjLCbR8SON/2vlwgLLMNX7GGMsdCFQN2vu0EMDmDiY5DET8OhQDo9DBqMIpHh2faKaBJT9UiImkNq/4LEUkxTQuCPDVTz0Gi92pVfYjXSS9l03z0RXp5iszVlhkq5sQTHEFWBn2bQE28WV3bJppFeE7rvOcYsgBA76a8tQKttXPEWlIlr7JP+b13vuFu/FHL9H0ZwXOiWqtNLJtcjlqDxVw2elX3Fwro4MaLatXToeTjxQ/FmcrEA9IpTX7P0apZwkKsSkEGYSsRnZkrydD5lfVWKB5Qq/5oadlJ6gy7DTTsaJ1ZuWtoG1xA3oQ5t2jmIwB1gCC1lmuAmDkVEXlJcK208lL33FInu4rtNK2acJcvU3cZkJDOI2XTkfYWOltflKyMyrBRkdY2V8Cmmv8h0+U1LH614JGQr5xOymv46FaqJGmQh7ZyJM+ST+4FJv3hMnA99EX2
    admin-user: AgAhITRt3hKP6L5A+cs/n9hAcgH6RXrpjj0XnBvi99YG7gK6pFLfyQ7JTQk2/aAbYuxK6vbjVU6W4aKVRZk75MpyIssulcJAB3xiQbVGqyVwZfSLaKasZcYx+ZiSCIptDVhijXCp7hsFMBFX5rYDP8lP/DjvTzT8q1qeztcbAtt8yfL0Cy+IW+CFqwqHnAWi+MXXAfTMr+xVuidnz5WlRIWXMdCf5LCe91d/QHh7Z4ueQw7dYWJL43qKrUlzpbBihTaOZcn9mA7+4X75y8g/6Pb6vg8SC2tMNFUHGNehtMCuh6lfxsJA5BNvRMbKWkvw8CIzMFz+wawVZV0V5/IjpC7qoxHB/zCepGOT6hsvjEmU1MmZVQC5Gq+zM1wVlFEJZNYcgR/qKPkLDpIEzFYFWQK33Hrk7DVpm7HhmrNu44MdcgOSwB/0ALEDBHNtIinxSxlNsAIiZLy6B+My9M1E1z0KbhBAzx1mRz7okQnUJnQvyfwWZMPjvr8Gj95goD95RVvmHAz3Uk0APF70Wp8fWtfBGJ5EvF/5Qy4/J0w6OzCl/BdSIjnirEnG/IsF9e1dPgNX57oZ1UNVN10LN6uf1jFA/cKfgMiyIIVgtmadBQt03feJkoHjD+1j1Np9cBf4CxihBADpNDnjM1RZDO+TklcHdwMvRaL7PcghCJVZtfRvJ+Hn331GqnCHl902qmSXnwAWN23bAg==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
