---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-postgres-reader
  namespace: monitoring
spec:
  encryptedData:
    password: AgC3fVBXm9tfgq5pDZGzbtEcr6LjUiBKPuz9EEQW/1kRg0gAh4ditQqp6zetNL0QgaNY+CYSXqaaMfnaxE3ORf5UFEEyv7UO5Pn1U9DPR/5N3L1CM+0De2c6iTcO8hX9INmkRc8jXtcNqIMihzjMObCWZ6dlza9nmZ+tqcz4VXPLsvQ7byWc7C70W9kse2e67XRHlDXdsiPvCo4plpaBx/TvTQgYfSNi4pxLmMa2WhsLkNIyUU2BkaaWLSbM6yiFjk5GOnfIMakOG3V+pqxSehLvmAfSNEFIHw2b1RwKOpwDqLY/MvQLVx8g5KV4Yc9WNDOiZnqObVyKQL0u6/In5eJjigfV5TPd27/rnyceRYgCha8OWGpn1W9sDKJMWfnz6aZ/bwUgEUgCfXG79h8UWAa/CCddl/7dTq7axpuJoKjX/hkZ1EEUTAyhOGmapovgnOE0QFdjNhRJeUiwYHnIBDqZSQJD6AC2rgImTIfDyIzNpkX2iZT5PEDMpd8xoNMyvnX5vrxFv41hLQYQRT304utxMTCQ/uRGw0qGp6xWYnQgtML9f1rNJ1ro53mzWJHMJdEmtPui9tzESSETqLieUDA89jGJ/cKjBPgfwaQd3apfSIrm1fmXkXrFLQQDBG0ZRmDQIeMHDeHtlTeDhr7A0xsdobq5XBX6WQyyz0d5h7P+e/5+X716J+Q5CWA0z5NCxTf+T8fvAkg8zgZofEuvN8ibg/lVT6tG
    username: AgBfExR0XVMhdMRsRNYeIwt/uQjYPF0AvAUU3NsGpEYJ9CW5RundGqXfOl9/okppTmnDPwf29S+iDzq96qTASCne8FIz+k8Wy8c6tAby/YYDtgmjG92cFCQTGLOZIGmclWmlEqlYL8qAdP4pi4EdTvnNt8cQnYxbBZMWotyYYRdQ0PJf5TFPRUzLSUwDFRbOjdIbJx/jr8sKFGYzHVXXIYDlW+zTtyan24po4g1xJsd2E8o2QRbFYrHyUH7BwKrcPpoWpj2KsgekG7Poxb/uIWn+wQL23lrQ2O/krXbeowCJa23cgCXg/4Xdqg/G+XsHgN6cYXmBwN/W2p6y/dj2hjHv/Ee0m1hpANc1LHjdMQtO/2Uj4WeRjIdb3fFrhr6jsxPnx4UJxMiXVrwoP1DmxKBjcBX1VEulug2OSWY6lRETJCXWgAIJgb65z/FxvS4uxM27A+MOn2FwSANsBf8HXqxYpCxMNIU8QRET2YLzZvlLZpkDbXJ8CTEMJsnzdZV5DI8BqGZgWn2o2i7axlYty6tE1L2LcpXa2nfSgCquP+sSjHUABlVqCXdRtMDXKHfhCuFicAOdcQ6DkEegL++p2RaPgN7okxzxCzS9yJ9u0MKMncqZ0hhsLZlOmQJs3CxaZehYwJNavycOQeQSozaUhWGLkn/5eriRU8DKLboXEtxWEhzfy92KXpnuHFnP1B5vAv2s5awZpk+/Q/vy5Np3vw==
  template:
    metadata:
      name: grafana-postgres-reader
      namespace: monitoring
