---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: dev
spec:
  encryptedData:
    password: AgDMbpt0/8zx3Snj69jNE3SbpUBKrRV9FYnSGeM8TEWG7HwwWrMSbzrg1/tOebmobJJNRr8h5hGjVxNa3aXqkscpra6pjwd+mGJvkSMS70XYSMVvZOaEKyg8oddlrh3KP69SQutlAPRhraQXQrYxUX/NIR3nIs2SVIyNCcAE+TMz7V07AMK3cDfyMwHBRDmj/EnL7eDQgnFRYWbtwFczDeZWrhgzzEu/hPMrRuo38sBFNxcXGK1WCKBcyVM+6ViGZCDFTJRdkwZZDeKYgYAKl2Si815fgwKIFZOizzGhg43W6uCg/s/nrbq4LoonjBbthRS3kXdI/xwFK5zyLqC+2lRk4HNTa0F1VjtEG3GgnWXtsyXit5S/rgZr0ToE2iuQNSYGQzJli9uIhq//DHJiJEggbvb+lOG915QuBbcvD2bMVYiMnFW6nLmMRun66+fFcbSYpuGd8an01KMPBsute8Nk5Gu+QtXr2wTArYQzwK9TAU6A1gcQycWJjhcaFM0FqiIIHS61dqocZJKIT1icq9/Jv4nWldCkA4Lpi1GBp82Ya2YmHtXoNrF4XL4EVos4RB0pwA6+NVX4d/w57RI1dJv1qT5+B4ejUuSbsXi9c1pkKBiC6xuz6J0LvQNtD4kfUCiF2t+nB7o3R0QH4eJB4AJt9rP59QkoizgfOraVnkksc7Thc20bKY4ygY1QzvCKLGzxhm4EdXZHkbS04oDyo/T8lw/BQMLvtw9AB1RLjCzW1f74Vxy6K8Mc48Qn58xsbJQ=
    user: AgAXYPjbq9pZFz/b+/y3ueAhOUYjbGPondQ0Ox0gZ6DL+5S+Cg0Oa/VTLfCwq8rlwbBCw8v+6skFW7GmTrefmRg8oV7wRIP1/vDNNaK6CJDrUlIzDncmqaxjMqbr9P33P2qR3XQFO6taEx8t6LgBXU7R46FoadGQ+agwe0WXoVx5dwlaA5m+/KGAcnzFysiJUkIWe4pGm0oqHRv9cS2VB4U9MNmeiClnF8OIyXQFrIMI/Zm7fhXD547oHZQVSVBNNsf9Ig+YEOlvHQV0hj6VOoRtRN+1cJ4Jn873V5uLKOL2WmF7u36Mn5aCTPeEH78C2VoZONa96yceP+bNnaeDLbbEkH7eeMH7/YrcQcE5PjdGlellqNMO3qfvkKjLEapU+JU4TTagpoIjkp8jIXRAVzi1ClRt+lACXa3l8aO7/QYlZLIW/1+1X/WPyYfHgENpxHyKQYqQcKhz5e/bC3IbrgJEP9N0PWfriakp54RfsRhf8c3t+hQx9o726iGBTe3vkBWwtIKb8nU3mwzHGnfEEBXOl2AqvXA5VxyZnZfJluqGDwil9UnEBiVw532bi05M8Vfgzuqp0KGm/9nfh85Mnz/muLAvfeOuE1krjICicJ93fIuJ8Z2Rj9OYth4W5qcli6oHhF4CqhxAckzz36+S3mU5g+eT8fFootAiVEGNV9IIAt8285njKhetS9X523lbQE12QbM=
  template:
    metadata:
      name: postgres-credentials
      namespace: dev
